type Todo {
  id: ID!
  task: String!
  createdAt: String!
  updatedAt: String!
}

type Query {
  todos: [Todo!]!
  todo(id: ID!): Todo!
}

type Mutation {
  createTodo(task: String!): Boolean!
  updateTodo(id: ID!, task: String!): Boolean!
  removeTodo(id: ID!): Boolean!
}
