type File {
  id: Int!
  name: String!
  type: String!
  url: String!
}

scalar FileScalar

type Mutation {
  deleteFile(fileId: Int!): Boolean!
  uploadFile(file: FileScalar!): String!
}

type Query {
  file(id: Int!): File!
  files(skip: Int, take: Int): [File!]!
}