scalar Date

type Task {
  id: ID
  task: String
  createdAt: Date
  updatedAt: Date
}

type Query {
  getAllTasks: [Task]
  getTask(id: ID): Task
}

type Mutation {
  newTask(task: String): Task
  editTask(id: ID, task: String): Task
  deleteTask(id: ID): Task
}
